version: 0.0.1.{build}
image: Visual Studio 2017

environment:
  matrix:
  - BUILD_OPTION: "Visual Studio 15 2017"
  - BUILD_OPTION: "Visual Studio 15 2017 Win64"

install:
  - choco install doxygen.portable

build_script:
- cmd: scripts\appveyor\build.cmd

test_script:
- cmd: scripts\appveyor\test.cmd
