language: cpp
dist: bionic

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-9
    - lcov
    - libgtk-3-dev
    - doxygen

matrix:
  include:
  - env: TEST="Build on macOS"
    os: osx
    osx_image: xcode11.6
    script: scripts/travis/build_macos.sh
  - env: TEST="Build on Linux"
    os: linux
    script: scripts/travis/build_linux.sh
  - env: TEST="Coverage"
    os: linux
    script: scripts/travis/coverage.sh
